run:
  build-tags:
    - testtools

    # golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: v1.62.0 # pin version to not introduce new linters unexpectedly

linters-settings:
  govet:
    auto-fix: true
    enable-all: true
    disable:
      fieldalignment
  revive:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
  misspell:
    locale: US
    auto-fix: true
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
  gofumpt:
    extra-rules: true
  whitespace:
    auto-fix: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - gofmt
    - gocyclo
    - ineffassign
    - stylecheck
    - misspell
    - staticcheck
    - unused
    - prealloc
    - typecheck
    # additional linters
    - bodyclose
    - gocritic
    - err113
    - goimports
    - revive
    - misspell
    - noctx
    - stylecheck
    - gosec
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - gochecksumtype
    - nilerr
    - reassign
    - whitespace
  enable-all: false
  disable-all: true

issues:
  exclude-files:
    - "(.*/)*.*_test.go"
    - "fixtures.go"
    - "dell.go"
    - "smc.go"

  exclude-rules:
    - linters:
        - gosec
      text: "weak cryptographic primitive"

    - linters:
        - stylecheck
      text: "ST1016"
exclude-use-default: false
