testonly: False
with-expecter: True
packages:
  github.com/metal-automata/rivets/events:
    config:
      dir: events/
      fileName: "mock_{{.InterfaceName | firstLower}}.go"
      inpackage: True
    interfaces:
      Message:
      Stream:
